# Generated by Django 5.2.8 on 2025-11-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_delete_testingdatabase_remove_studentaccount_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
