# Generated by Django 5.2.8 on 2025-11-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_studentinformation_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/default_profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
